#!/bin/sh
# Runs as root only long enough to lock the network, then drops to the agent uid with no caps.
# Any failure here exits non-zero: the agent never starts without the firewall (fail closed).
set -eu
: "${AGENT_UID:?}" "${AGENT_GID:?}" "${ALLOW:?}"   # ALLOW="ip:port ip:port ..."

for t in iptables ip6tables; do
  $t -P INPUT DROP; $t -P FORWARD DROP; $t -P OUTPUT DROP
  $t -A INPUT -i lo -j ACCEPT;  $t -A OUTPUT -o lo -j ACCEPT
  $t -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
  $t -A OUTPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
done
for spec in $ALLOW; do   # IPv4 tcp allowlist; IPv6 stays fully closed
  iptables -A OUTPUT -p tcp -d "${spec%:*}" --dport "${spec##*:}" -j ACCEPT
done
# everything else (incl. DNS: names come from --add-host) is refused fast, not hung
iptables -A OUTPUT -p tcp -j REJECT --reject-with tcp-reset
iptables -A OUTPUT -j REJECT
ip6tables -A OUTPUT -j REJECT

# Hermes config: bind-mounted read-only from the host (.hermes/config.yaml, generated by
# run.sh from the template) — the agent cannot repoint its model or disable the guard plugin.
# The named volume under it holds sessions/logs; it starts root-owned, so chown the dir.
mkdir -p /home/agent/.hermes-home
chown "$AGENT_UID:$AGENT_GID" /home/agent /home/agent/.hermes-home

# The gateway is the agent's only path to a model (config.yaml above points there): budgets,
# allowed models, injection screening, PII screening, audit. Background child of the agent,
# same uid — it inherits the firewall and the zero-cap setpriv session.
exec setpriv --reuid "$AGENT_UID" --regid "$AGENT_GID" --clear-groups \
  --inh-caps=-all --bounding-set=-all --no-new-privs -- sh -c '
    /opt/venv/bin/python -m src.guard.gateway --listen 127.0.0.1:8787 1>&2 &   # banner na stderr: stdout execniętego polecenia czysty
    gw=$!; trap "kill $gw 2>/dev/null" EXIT INT TERM
    i=0
    while ! /opt/venv/bin/python -c "import socket;socket.create_connection((\"127.0.0.1\",8787),timeout=1)" 2>/dev/null; do
      kill -0 $gw 2>/dev/null || { echo "guard gateway died" >&2; exit 1; }   # no gateway = no model door: fail closed
      i=$((i+1)); [ $i -gt 50 ] && { echo "guard gateway did not come up" >&2; exit 1; }
      sleep 0.2
    done
    exec "$@"' _ "$@"